### ISSUE TITLE
A very simple Windows Bat file

### ISSUE THREAD

**Issue by scweeny** [DoumanAsh/syosetu-dump#1]
It's not fancy.
But I've created a Bat file that makes it easy to use this program in a Windows environment.
I thought it would be nice to add it to the distribution for Windows, thanks.
[Download.zip](https://github.com/user-attachments/files/16647260/Download.zip)

**Comment by DoumanAsh** [comment]
I see, I normally use console on my windows machine so I never considered to make it more friendly 
But I could probably modify interface to present prompts for use to enter parameters instead of expecting user input by default

Feel free to make PR to just add script for now though

**Comment by DoumanAsh** [comment]
I made quick change to allow for simple prompts to configure parameters
![syosetu-dump_1723970365](https://github.com/user-attachments/assets/87ab7907-e7ac-45ff-9c39-c5c10a535a18)


This should get it simpler to get started without need for you to write BAT files

**Comment by DoumanAsh** [comment]
Refined it a bit to make it more convenient for opening it from file explorer
![syosetu-dump_1723971554](https://github.com/user-attachments/assets/96cd5820-2380-4d2d-ba4f-1b56f9d6af3f)

**Comment by scweeny** [comment]
> 파일 탐색기에서 열 때 더 편리하도록 조금 개선했습니다. ![syosetu-dump_1723971554](https://private-user-images.githubusercontent.com/5676053/358894948-96cd5820-2380-4d2d-ba4f-1b56f9d6af3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzgyMjcsIm5iZiI6MTcyMzk3NzkyNywicGF0aCI6Ii81Njc2MDUzLzM1ODg5NDk0OC05NmNkNTgyMC0yMzgwLTRkMmQtYmE0Zi0xYjU2ZjlkNmFmM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MThUMTA0NTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWI4NjMxYmZlYzU0NDU5NWMyODRlNzIxOTliNTNhODRlNzcxODkwZjMzZGM0NjIwZjU2ZDYwYzUwNTA5OGM2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0o7gzkY67GPlTeOjreqx8GAVHoNI-WGb30iSn7tBjCU)

It looks very nice, thank you.
