### ISSUE TITLE
Site change breaking parser - 2024/09/18

### ISSUE THREAD

**Issue by scweeny** [DoumanAsh/syosetu-dump#2]
![이미지1491](https://github.com/user-attachments/assets/85ab90ad-1e86-4a7a-9473-8c6373db2c11)

=================================

Most likely, the internal structure of your site has changed.

**Comment by DoumanAsh** [comment]
Hm yeah it seems they removed id from novel body element
I will check HTML and update it

**Comment by scweeny** [comment]
![이미지1492](https://github.com/user-attachments/assets/e7f37a23-6712-4acb-8868-0884c78caf1b)

When I checked the source code, I realized that the internal structure of the site had changed.

**Comment by DoumanAsh** [comment]
@scweeny Yeah, I can see thanks for sample
I will let make updated version soon
It is annoying, but unfortunately common thing

**Comment by DoumanAsh** [comment]
@scweeny I made new release https://github.com/DoumanAsh/syosetu-dump/releases/tag/1.3.2
It will work now without issues I hope
At least I didn't have issues to download novel you wanted to download

**Comment by scweeny** [comment]
As always, thank you.
